spring:
  datasource:
    url: jdbc:h2:~/data/booklog;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    properties:
      hibernate:
        show-sql: true
        format_sql: true

jwt:
  secret: thisisabooklogscretkeykyuwonsdfs
